### PR TITLE
Fix genesis block bug with KIP71 parameters

### LINKED ISSUE #1375: Implement contract-based governance mode
Implement an on-chain governance that stores governance parameters in a smart contract.

## Step 1. Syntactic sugars

Until v1.9.0.
Merge into `dev` branch.

- Encapsulate `Governance` type behind `Engine` interface
   - https://github.com/klaytn/klaytn/pull/1297
   - https://github.com/klaytn/klaytn/pull/1298
- Add `GovParamSet` type as a parameter data model
   - https://github.com/klaytn/klaytn/pull/1303
   - https://github.com/klaytn/klaytn/pull/1377
- Add `Engine.Params()` and `Engines.ParamsAt()` that can replace all other parameter getters
  - https://github.com/klaytn/klaytn/pull/1380

## Step 2. Load parameters from contract

Target: v1.10.0.
Merge into `dev` branch.

- Update chainconfig and homi
  - #1512
  - #1639
  - #1640 
- Replace parameter getters by `Engine.Params()` and `Engines.ParamsAt()`
  - https://github.com/klaytn/klaytn/pull/1604
- Add `GovParam.sol` and `ContractEngine` 
  - https://github.com/klaytn/klaytn/pull/1614
- Enable `ContractEngine` by hardfork and voting
  - https://github.com/klaytn/klaytn/pull/1623
- Collateral Bugs
  - Fix Genesis.ChainConfig.Reward.Kip71 was not correctly loaded

### PR DESCRIPTION
**Pull request by ian0371**
## Proposed changes
This PR
- inserts the KIP71 parameters from `genesis.json` to the genesis block
- adds missing params in ToChainConfig()
- handles empty GovParam address in headergov
- changes Reward functions to receive `Rules` and `GovParamSet`
- close #1375

### 1. Inserting the KIP71 parameters from `genesis.json` to the genesis block

If nodes were created as follows, it will be problematic:
```
homi setup local --cn-num 1 --governance
# ...
cat homi-output/scripts/genesis.json
...
    "magmaCompatibleBlock": 0,
...
    "kip71": {
        "lowerboundbasefee": 0,
        "upperboundbasefee": 0,
        "gastarget": 0,
        "maxblockgasusedforbasefee": 0,
        "basefeedenominator": 0
    }
...
```

Output:
```
ERROR[11/21,17:59:48 +09] [51|work/worker.go:539]  Failed to prepare header for mining       err="invalid baseFee: have 25000000000, want 0, parentBaseFee 25000000000, parentGasUsed 0"
```

This is because the genesis block's baseFee contains the default LowerBoundBaseFee.

To address this issue, following logic needs to be updated:
- ToBlock(): Respect `genesis.json` lowerboundbasefee instead of default
- GetGovernanceItemsFromChainConfig(): returns magma or kore parameters if the genesis block is magma or kore, resp.

SetDefaults() must ignore new parameters (magma, kore, and so on) if they're not present in `genesis.json`.
So we rename SetDefaults() -> SetDefaultsForGenesis(), and introduce SetDefaults() for ChainConfig initialization in `node/cn/backend`.

### 2. Adding missing params in ToChainConfig()

GovParamContract was missing

### 3. Handling empty GovParam address from headergov

If GovParam address has not been voted, it could be empty even after Kore hardfork.
So, we regard this situation ContractEngine-disabled.

- Describe your changes to communicate to the maintainers why we should accept this pull request.
- If it fixes a bug or resolves a feature request, be sure to link to that issue.

### 4. Changing Reward functions to receive `Rules` and `GovParamSet`
If `governance = "null"` in `genesis.json`, kip82ratio was missing when the node starts.
It could result in `Crit` when trying to parse an empty kip82ratio with `parseRewardKip82Ratio`.
To avoid this situation, we make sure it falls back to the default kip82 ratio by using ParamsAt() in `Finalize()`, and change the parameters of Reward functions as well.

## Types of changes

Please put an x in the boxes related to your change.

- [ ] Bugfix
- [ ] New feature or enhancement
- [ ] Others

## Checklist

*Put an x in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.*

- [ ] I have read the [CONTRIBUTING GUIDELINES](https://github.com/klaytn/klaytn/blob/master/CONTRIBUTING.md) doc
- [ ] I have signed the [CLA](https://cla-assistant.io/klaytn/klaytn)
- [ ] Lint and unit tests pass locally with my changes (`$ make test`)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Related issues

- Please leave the issue numbers or links related to this PR here.

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by blukat29 — APPROVED** [review]

File: governance/default.go [hunk 1]
```diff
@@ -1108,12 +1116,35 @@ func GetGovernanceItemsFromChainConfig(config *params.ChainConfig) GovernanceSet
...
+		config.Governance.KIP71 != nil {
+		kip71 := config.Governance.KIP71
+		governanceMap := map[int]interface{}{
+			params.LowerBoundBaseFee:         kip71.LowerBoundBaseFee,
+			params.UpperBoundBaseFee:         kip71.UpperBoundBaseFee,
+			params.GasTarget:                 kip71.GasTarget,
+			params.MaxBlockGasUsedForBaseFee: kip71.MaxBlockGasUsedForBaseFee,
+			params.BaseFeeDenominator:        kip71.BaseFeeDenominator,
+		}
+
```
Comment (hyunsooda) [inline governance/default.go:1133]:
```suggestion
```

File: governance/default.go [hunk 2]
```diff
@@ -1108,12 +1116,35 @@ func GetGovernanceItemsFromChainConfig(config *params.ChainConfig) GovernanceSet
...
+	}
+
+	// kore params
+	if config.IsKoreForkEnabled(common.Big0) &&
+		config.Governance != nil {
+		governance := config.Governance
+		governanceMap := map[int]interface{}{
+			params.GovParamContract: governance.GovParamContract,
 		}
+
```
Comment (hyunsooda) [inline governance/default.go:1144]:
```suggestion
```

File: governance/default.go [hunk 3]
```diff
@@ -1108,12 +1116,35 @@ func GetGovernanceItemsFromChainConfig(config *params.ChainConfig) GovernanceSet
...
+		appendToReturn(governanceMap)
+	}
+
+	// kore params
+	if config.IsKoreForkEnabled(common.Big0) &&
+		config.Governance != nil {
+		governance := config.Governance
+		governanceMap := map[int]interface{}{
+			params.GovParamContract: governance.GovParamContract,
 		}
```
Comment (hyunsooda) [inline governance/default.go:1143]:
```suggestion
		governanceMap := map[int]interface{}{
			params.GovParamContract: config.Governance.GovParamContract,
		}
```

File: governance/default.go [hunk 4]
```diff
@@ -1108,12 +1116,35 @@ func GetGovernanceItemsFromChainConfig(config *params.ChainConfig) GovernanceSet
...
+		appendToReturn(istanbulMap)
+	}
+
+	// magma params
+	if config.IsMagmaForkEnabled(common.Big0) &&
+		config.Governance.KIP71 != nil {
+		kip71 := config.Governance.KIP71
+		governanceMap := map[int]interface{}{
+			params.LowerBoundBaseFee:         kip71.LowerBoundBaseFee,
+			params.UpperBoundBaseFee:         kip71.UpperBoundBaseFee,
```
[the remark this answers is not in the document]
Comment (ian0371) [reply governance/default.go:1128]: LowerBoundBaseFee will be set from genesis.json, but UpperBoundBaseFee will be set as an empty value (0).
There's no check, so it will show an undefined behavior.

File: blockchain/genesis.go [hunk 5]
```diff
@@ -330,10 +330,14 @@ func (g *Genesis) ToBlock(baseStateRoot common.Hash, db database.DBManager) *typ
...
 		head.BlockScore = params.GenesisBlockScore
 	}
-	// TODO-klaytn should set genesis block's base fee
 	if g.Config != nil && g.Config.IsMagmaForkEnabled(common.Big0) {
-		head.BaseFee = new(big.Int).SetUint64(params.DefaultLowerBoundBaseFee)
+		if g.Config.Governance != nil && g.Config.Governance.KIP71 != nil {
+			head.BaseFee = new(big.Int).SetUint64(g.Config.Governance.KIP71.LowerBoundBaseFee)
+		} else {
+			head.BaseFee = new(big.Int).SetUint64(params.DefaultLowerBoundBaseFee)
+		}
```
Comment (hyunsooda) [inline blockchain/genesis.go:338]: This change seems to fix the existing bug that fails to retrieve validators.

**Review by hyunsooda — COMMENTED** [review]
`starting from v1.10, if magma hardfork block is 0, KIP71 parameters are used from genesis.json if present` seems misleading. The current change seems still set KIP71 params even the KIP71-compatible blk number is not zero. What was your initial purpose? or am I wrong?

**Comment by kjeom** [comment]
I have tested followings with dev branch which this PR is not merged yet.
- `kcn init genesis.json with kip71` : `chainConfig` and `itemsAt` shows `kip71` in genesis.json
- `kcn init genesis.json with updated kip71` again : `chainConfig` and `itemsAt` shows the `updated kip71` in genesis.json

File: governance/default.go [hunk 6]
```diff
@@ -1075,9 +1075,21 @@ func (gov *Governance) GetTxPool() txPool {
 	return gov.TxPool
 }
 
+// GetGovernanceItemsFromChainConfig returns governance set
+// that is effective at the genesis block
 func GetGovernanceItemsFromChainConfig(config *params.ChainConfig) GovernanceSet {
 	g := NewGovernanceSet()
 
+	// append to the return value `g`
+	appendToReturn := func(govmap map[int]interface{}) {
```
[the remark this answers is not in the document]
Comment (ian0371) [reply governance/default.go:1084]: How about renaming `g` to `govSet` and renaming `appendToReturn` to `addGovMapToGovSet`?

File: params/config.go [hunk 7]
```diff
@@ -436,6 +434,16 @@ func (c *ChainConfig) SetDefaults() {
...
 }
 
+// SetDefaults fills undefined chain config with default values
+// so that nil pointer does not exist in the chain config
+func (c *ChainConfig) SetDefaults() {
+	c.SetDefaultsForGenesis()
+
+	if c.Governance.KIP71 == nil {
+		c.Governance.KIP71 = GetDefaultKIP71Config()
+	}
```
[the remark this answers is not in the document]
Comment (ian0371) [reply params/config.go:444]: As mentioned in the PR description,
> SetDefaults() must ignore new parameters (magma, kore, and so on) if they're not present in genesis.json.
So we rename SetDefaults() -> SetDefaultsForGenesis(), and introduce SetDefaults() for ChainConfig initialization in node/cn/backend.

Let me know if this is still confusing.

File: governance/default.go (hunk 2 above)
Comment (ian0371) [reply governance/default.go:1144]: Do you mean deleting all LFs above before `appendToReturn`?

Comment (ian0371) [reply governance/default.go:1144]: there are 4 of them

**Comment by ian0371** [comment]
> `starting from v1.10, if magma hardfork block is 0, KIP71 parameters are used from genesis.json if present` seems misleading. The current change seems still set KIP71 params even the KIP71-compatible blk number is not zero. What was your initial purpose? or am I wrong?


@hyunsooda 

You're right. I meant to say that the parameters will be present in the genesis block. I'll fix it

**Review by kjeom — APPROVED** [review]

File: governance/default.go (hunk 3 above)
Comment (ian0371) [reply governance/default.go]: fixed in 9a0acef

File: governance/default.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (blukat29) [reply governance/default.go:1086]: My personal preference is `govSet` and `appendGovSet()`.

**Review by blukat29 — APPROVED** [review]

File: params/config.go (hunk 7 above)
[the remark this answers is not in the document]
Comment (hyunsooda) [reply params/config.go:445]: I see. I didn't know there was another caller of SetDefaultsForGenesis (called at initGenesis). If I understand it correctly, the correct description should be `if they're present in genesis.json.`, not `if they're not present in genesis.json.` Correct?

File: governance/default.go (hunk 2 above)
Comment (hyunsooda) [reply governance/default.go:1146]: Yes, but it's okay to go over.

File: params/config.go (hunk 7 above)
[the remark this answers is not in the document]
Comment (ian0371) [reply params/config.go:445]: No, the latter is correct. If a user did not specify KIP71 parameters in genesis.json, they're not going to be contained in the genesis block. Thus, SetDefaultsForGenesis() should be ignoring them.

**Comment by hyunsooda** [comment]
Works now. https://github.com/klaytn/klaytn/pull/1711/commits/b01f8f3b7aa69afc1f7693e652adc5f2d8fa4ab6 fixes the issue. Let me put one concern, Nil check is not needed for reward property? (e.g., `config.Governance.Reward` is directly accessed without nil check).

**Comment by ian0371** [comment]
@hyunsooda You're right. fixed in 4e371987. Thanks

**Review by blukat29 — APPROVED** [review]

File: consensus/istanbul/backend/engine.go [hunk 8]
```diff
@@ -453,10 +453,15 @@ func (sb *backend) Finalize(chain consensus.ChainReader, header *types.Header, s
 	}
 
 	var rewardSpec *reward.RewardSpec
-	var err error
+
+	rules := chain.Config().Rules(header.Number)
+	pset, err := sb.governance.ParamsAt(header.Number.Uint64())
```
Comment (jiseongnoh) [inline consensus/istanbul/backend/engine.go:458]: maybe pSet? parameter set?

Comment (blukat29) [reply consensus/istanbul/backend/engine.go:458]: Let's fix it later.

Comment (ian0371) [reply consensus/istanbul/backend/engine.go:458]: Other codes use pset as well, so we'll update to update them all...

File: reward/reward_distributor_test.go [hunk 9]
```diff
@@ -252,17 +253,22 @@ func TestRewardDistributor_getBurnAmountMagma(t *testing.T) {
...
-	config.MagmaCompatibleBlock = big.NewInt(0)
+	var (
+		header = &types.Header{
+			Number: big.NewInt(1),
+		}
+		rules = params.Rules{
+			IsMagma: true,
+		}
+		pset, _ = params.NewGovParamSetIntMap(map[int]interface{}{
+			params.UnitPrice: 0, // unused value because Magma
```
Comment (jiseongnoh) [inline reward/reward_distributor_test.go:264]: typo

Comment (jiseongnoh) [inline reward/reward_distributor_test.go:264]: unused value because of Magma

**Review by jiseongnoh — APPROVED** [review]
Looks good to me!

**Review by jeongkyun-oh — APPROVED** [review]
