### PR TITLE
cmd: move unlock logic to the end of startNode to fix temporary bad block when node starts

### LINKED ISSUE #1103: A bad block occurs when downloader starts before the node's init job is done
**Describe the bug**
When a node starts, a bad block appears if the downloader starts before the whole node's init job is done.
Then, it doesn't reproduce a bad block any more after it downloads the identical block from the other peer.

**How to reproduce**
step1. make a node's init job heavy (ex. unlock 20 or more local accounts)
step2. start up a cypress or baobab en.

**Expected behavior**
No bad block appears.

**Environment (please complete the following information)**
 - Klaytn version: v1.7.3
 - go version: v1.17.5
 - ubuntu20.04

### PR DESCRIPTION
**Pull request by yoomee1313**
## Proposed changes
- It moves unlock logic to the end of `startNode`.
- It fixes #1103.
- It seems the node used uninitilialized istanbul chainConfig because sync starts before istanbul chainConfig is set.

closes https://github.com/klaytn/klaytn/issues/1103

## Types of changes

Please put an x in the boxes related to your change.

- [x] Bugfix
- [ ] New feature or enhancement
- [ ] Others

## Checklist

*Put an x in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.*

- [x] I have read the [CONTRIBUTING GUIDELINES](https://github.com/klaytn/klaytn/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla-assistant.io/klaytn/klaytn)
- [x] Lint and unit tests pass locally with my changes (`$ make test`)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Related issues

- Please leave the issue numbers or links related to this PR here.

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: cmd/utils/nodecmd/defaultcmd.go [hunk 1]
```diff
@@ -120,6 +110,17 @@ func startNode(ctx *cli.Context, stack *node.Node) {
 	} else {
 		startKlaytnAuxiliaryService(ctx, stack)
 	}
+
```
Comment (aidan-kwon) [inline cmd/utils/nodecmd/defaultcmd.go:113]: You mean that the above code should be finished earlier than other code being executed in another goroutine. So, you move the following code at the bottom of the function, right? Can you explain details about the disorder of which goroutines makes the bad block issue? 
Your change seems that it can mitigate the issue somewhat, but cannot resolve it completely.

Comment (aidan-kwon) [reply cmd/utils/nodecmd/defaultcmd.go:113]: I think this change is okay if we need lots of engineering to resolve the issue, but we need to figure out whether other race issues can occur because of the same reason.

Comment (yoomee1313) [reply cmd/utils/nodecmd/defaultcmd.go:113]: @aidan-kwon It seems that the node used uninitilialized istanbul chainConfig because sync starts before istanbul chainConfig is set.

The following functions are called to set istanbul chainConfig. startKlaytnAuxiliaryService -> cn.StartMining -> go s.miner.Start() -> self.worker.start() -> istanbul.Start -> sb.SetChain(chain)

At sb.SetChain(chain), `chainConfig` is set by setting `chain` to `sb.chain`. So, I changed the code to call `startKlaytnAuxiliaryService` earlier than the unlocking process.

Comment (aidan-kwon) [reply cmd/utils/nodecmd/defaultcmd.go:113]: I cannot get the explanation. As far as I know, the moved code is not affected by chainConfig. What is the code using uninitilialized istanbul chainConfig?

**Review by aidan-kwon — APPROVED** [review]

**Review by jeongkyun-oh — APPROVED** [review]
