### PR TITLE
fix incomplete pending block handling logic regarding API requests

### LINKED ISSUE #1842: "eth" namespace APIs can't handle "pending" block correctly.
Klaytn has separated the role of nodes into various types; block generation node (CN) and API serving node (EN), and others. "pending" block (self-generated block but not confirmed by other nodes) as an API request parameter is meaningless. Therefore, "klay" namespace APIs handle "pending" block parameter as "latest" block parameter. 

However, it seems that some "eth" namespace APIs are trying to handle "pending" block and it causes an error on the endpoint node. We need to investigate how "eth" namespace APIs handle "pending" blocks and replace them to use "latest" block instead.

### PR DESCRIPTION
**Pull request by aidan-kwon**
## Proposed changes

This PR contains two different fixes regarding "pending" block requests. 

1) panic because of the absence of pending block
Panic was reported in #1841 regarding API servicing with "pending" block parameter. The panic can be triggered when a pending block has never been created yet but a user requests API with "pending" parameter. 

2) occasional API error with  "invalid signature length" error message
During the synchronization, a node uses a worker's snapshot to return a pending block. The block is created with the worker's `current` data in `updateSnapshot()` method. Since EN doesn't create a pending block correctly, however, the `current.header` doesn't have enough information including a miner's signature. Therefore, `eth_getBlockByNumber` and other API fail to recover a block proposer's address and return an error message. This PR set the previous block header for a pending block of EN/PN to support the API correctly. 

## Types of changes

Please put an x in the boxes related to your change.

- [x] Bugfix
- [ ] New feature or enhancement
- [ ] Others

## Checklist

*Put an x in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.*

- [x] I have read the [CONTRIBUTING GUIDELINES](https://github.com/klaytn/klaytn/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla-assistant.io/klaytn/klaytn)
- [x] Lint and unit tests pass locally with my changes (`$ make test`)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Related issues

Resolve #1842

### CODE REVIEW

File: work/worker.go [hunk 1]
```diff
@@ -471,7 +477,9 @@ func (self *worker) makeCurrent(parent *types.Block, header *types.Header) error
 	}
 	work := NewTask(self.config, types.MakeSigner(self.config, header.Number), stateDB, header)
 	if self.nodetype != common.CONSENSUSNODE {
+		// set the current block and header as pending block and header to support APIs requesting a pending block.
 		work.Block = parent
+		work.header = parent.Header()
```
Comment (kjeom) [inline work/worker.go:482]: I didn't find any negative effect when setting the previous block header.

Comment (aidan-kwon) [reply work/worker.go:482]: @kjeom You mean that you can't find the current problem related to block header, right?

1. Currently, an incomplete block header is used for `makeCurrent` and the method set the header to `worker.current.header`.
https://github.com/klaytn/klaytn/blob/6833919f7de6acda298cd3c9ff779daf5cdbd93c/work/worker.go#L529-L543


3. `worker.snapshotBlock` consists of `worker.current.header` and others
https://github.com/klaytn/klaytn/blob/6833919f7de6acda298cd3c9ff779daf5cdbd93c/work/worker.go#L616-L620

4. `worker.snapshotBlock` can be returned as a pending block 
https://github.com/klaytn/klaytn/blob/6833919f7de6acda298cd3c9ff779daf5cdbd93c/work/worker.go#L220-L225

5. In the JSON marshaling logic, the pending block's header is used to calculate a block proposer address 
https://github.com/klaytn/klaytn/blob/6833919f7de6acda298cd3c9ff779daf5cdbd93c/api/api_ethereum.go#L1463-L1474

Therefore, an incomplete block header assigned to `worker.current.header` can cause panic. Since EN/PN doesn't finish the pending block generation process, an alternative header is needed for `worker.current.header`

Comment (kjeom) [reply work/worker.go:482]: @aidan-kwon Oh, sorry for confusing. I just noted what I have finished for review.
Anyway thanks for explaining it in detail.

**Review by blukat29 — APPROVED** [review]
