### PR TITLE
Fix reward miscalculation under RoundRobin policy

### LINKED ISSUE #1654: Implement KIP-82 reward mechanism
Implement [KIP-82](https://github.com/yeri-lee/kips/blob/temp/KIPs/kip-82.md).

- https://github.com/klaytn/klaytn/pull/1631
- #1692
  - #1709

### LINKED ISSUE #1692: Reward miscalculation under RoundRobin policy
**Describe the bug**

Klaytn node v1.9.1 seems to be miscalculating the amount of a block reward when all of the below conditions are met:
1. Proposer policy is RoundRobin
2. Reward config DeferredTxFee is false
3. Gas price is nonzero

Cypress and Baobab are not affected, but some service chains with the above configuration could be affected.

**How to reproduce**

First, run a local network with ProposerPolicy=RoundRobin and DeferredTxFee=false.
Set MintingAmount to 1 KLAY for brevity.
```
./homi setup --cn-num 1 \
    --governance --reward-mint-amount 1000000000000000000 \
    --docker-image-id klaytn/klaytn:v1.9.1
cd homi-output
docker-compose up -d
```

Then send a transaction, and see how much the miner reward has accumulated.
```js
docker-compose exec CN-0 kcn attach /klaytn/klay.ipc
> var A = personal.listAccounts[0]
> var N = "0x0000000000000000000000000000000000000000"
> klay.sendTransaction({ from: A, to: N, value: 1e+50 }); // Drain miner account

> klay.sendTransaction({ from: A, to: N, value: 0 }); // Send a test transaction
"0xba0ddb4fde1ab90511c6ecf69aaa50c1205a18ab20fc7d106f1869d3ae8aaa0d"
> klay.getTransactionReceipt("0xba0ddb4fde1ab90511c6ecf69aaa50c1205a18ab20fc7d106f1869d3ae8aaa0d").blockNumber
121

> governance.chainConfig.governance.reward.mintingAmount
1000000000000000000
> governance.chainConfig.governance.reward.deferredTxFee
false
> governance.chainConfig.istanbul.policy
0

> governance.chainConfig
{
  chainId: 1000,
  deriveShaImpl: 0,
  ethTxTypeCompatibleBlock: 0,
  governance: {
    governanceMode: "none",
    governingNode: "0x3d3da668c9ca5b28897351da25114164bde439f9",
    kip71: {
      basefeedenominator: 20,
      gastarget: 30000000,
      lowerboundbasefee: 25000000000,
      maxblockgasusedforbasefee: 60000000,
      upperboundbasefee: 750000000000
    },
    reward: {
      deferredTxFee: false,
      minimumStake: 2000000,
      mintingAmount: 1000000000000000000,
      proposerUpdateInterval: 3600,
      ratio: "100/0/0",
      stakingUpdateInterval: 86400,
      useGiniCoeff: false
    }
  },
  istanbul: {
    epoch: 604800,
    policy: 0,
    sub: 21
  },
  istanbulCompatibleBlock: 0,
  londonCompatibleBlock: 0,
  magmaCompatibleBlock: 0,
  unitPrice: 0
}
```

```js
> klay.getBlock(121).gasUsed
21000
> klay.getBlock(121).baseFeePerGas
"0x5d21dba00"

> klay.getBalance(A,120)
120000787500000000000
> klay.getBalance(A,121)
121001575000000000000
```

The reward given to the miner account (A) is 1 KLAY + 787500 ston.
```python
>>> # Acutal fee reward = balance(121) - balance(120) - 1 KLAY
>>> (121001575000000000000 - 120000787500000000000 - 1000000000000000000) / 1e9
787500.0
```

**Expected behavior**

The expected reward for the miner account (A) is 1 KLAY + 525000 ston
```python
>>> # Expected fee reward = block.gasUsed * baseFee
>>> 21000 * 0x5d21dba00 / 1e9
525000.0
```

**Attachments**

**Environment (please complete the following information)**
 - Klaytn version `docker klaytn/klaytn:v1.9.1`
 - go version `go1.18.4 darwin/arm64`
 - OS and its version `macOS/12.6`

**Additional context**

### PR DESCRIPTION
**Pull request by ian0371**
## Proposed changes
This PR
- fixes the bug in #1692
- closes #1654

Before Kore, there was a bug that distributed txFee at the end of block proecessing regardless of `deferredTxFee` flag.
See #1692.
To maintain backward compatibility, we only fix the buggy logic after Kore and leave the buggy logic before Kore.

## Types of changes

Please put an x in the boxes related to your change.

- [ ] Bugfix
- [ ] New feature or enhancement
- [ ] Others

## Checklist

*Put an x in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.*

- [ ] I have read the [CONTRIBUTING GUIDELINES](https://github.com/klaytn/klaytn/blob/master/CONTRIBUTING.md) doc
- [ ] I have signed the [CLA](https://cla-assistant.io/klaytn/klaytn)
- [ ] Lint and unit tests pass locally with my changes (`$ make test`)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Related issues

- Please leave the issue numbers or links related to this PR here.

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: reward/reward_distributor.go [hunk 1]
```diff
@@ -178,16 +178,16 @@ func GetBlockReward(header *types.Header, config *params.ChainConfig) (*RewardSp
...
-		// some non-zero fee is paid to the proposer.
-		if !config.Governance.Reward.DeferredTxFee {
-			blockFee := GetTotalTxFee(header, config)
-			spec.Proposer = spec.Proposer.Add(spec.Proposer, spec.TotalFee)
-			spec.TotalFee = spec.TotalFee.Add(spec.TotalFee, blockFee)
-			incrementRewardsMap(spec.Rewards, header.Rewardbase, blockFee)
-		}
+	// Compensate the difference between CalcDeferredReward() and actual payment.
+	// If not DeferredTxFee, CalcDeferredReward() assumes 0 total_fee, but
+	// some non-zero fee is paid to the proposer.
```
Comment (jiseongnoh) [inline reward/reward_distributor.go:185]: tx fees have been sent to the proposer?

File: reward/reward_distributor.go [hunk 2]
```diff
@@ -157,6 +157,12 @@ func GetTotalTxFee(header *types.Header, config *params.ChainConfig) *big.Int {
 	return totalFee
 }
 
+// config.Istanbul must have been set
+func IsRewardSimple(config *params.ChainConfig) bool {
+	policy := config.Istanbul.ProposerPolicy
+	return policy != uint64(istanbul.WeightedRandom)
```
Comment (jiseongnoh) [inline reward/reward_distributor.go:163]: I guess this code was meant to check the mainnet. Maybe we can refactor this some day...

**Review by jiseongnoh — APPROVED** [review]
