### PR TITLE
fix wrong return of api related to snapshot

### LINKED ISSUE #1467: Some APIs related snapshot return wrong values .
**Describe the bug**
When some APIs are called, APIs return wrong values that is related to snapshot.
The problem has been occurred with API list below.

- getCouncil
- getCouncilSize
- getValidators
- getValidatorsAtHash
- getDemotedValidators
- getDemotedValidatorsAtHash
- getSnapshot
- getSnapshotAtHash

**How to reproduce**
The pictures below show the problem situation.
The test environment consists of 4 nodes. So committee size and validators are equal.
In the picture, all APIs call block 296, but validators and committee values ​​are different depending on the API.
Because block 296 contains one valid removeValidator vote. Therefore, in block 297, committee size and validators are 3

**Attachments**
image (1)

image (2)

**Environment (please complete the following information)**
 - Klaytn v1.8.4+31b65eb1ab 
 - go version go1.18.2 darwin/arm64
 - macOS/12.4

### PR DESCRIPTION
**Pull request by mckim19**
## Proposed changes

As described in the previous issue #1467, some API calls return incorrect values.
This PR solves the problem and APIs below return correct values.
The API in ( ) is the function that calls the preceding function.
 
- getCouncil(getCouncilSize)
- getSnapshot(getValidators, getDemotedValidators)
- getSnapshotAtHash(getValidatorsAtHash, getDemotedValidatorsAtHash)

|                                	| Current implement (dev)        	| New implement  (PR)       	|
|--------------------------------	|------------------	|------------------	|
GetSnapshot(n) | api.istanbul.snapshot(n) | api.istanbul.snapshot(n)
GetSnapshotAtHash(n)  | api.istanbul.snapshot(n) | api.istanbul.snapshot(n)
GetCommittee(n) |  api.istanbul.snapshot(n-1) | **api.istanbul.snapshot**(n-1)
GetCommitteeSize(n)  | api.istanbul.snapshot(n-1) | **api.istanbul.snapshot**(n-1)
GetCouncil(n) | api.GetSnapshot(n) | api.istanbul.snapshot(**n-1**)
GetCouncilSize(n) | api.GetSnapshot(n) | api.istanbul.snapshot(**n-1**)
GetValidators(n) | api.GetSnapshot(n) | api.istanbul.snapshot(**n-1**)
GetValidatorsAtHash(n) | api.GetSnapshot(n) | api.istanbul.snapshot(**n-1**)
GetDemotedValidators(n) | api.GetSnapshot(n) | api.istanbul.snapshot(**n-1**)
GetDemotedValidatorsAtHash(n) | api.GetSnapshot(n) | api.istanbul.snapshot(**n-1**)

The test environment consists of 4 nodes. So committee size and validators are equal.
Block 304 contains one valid removeValidator vote. Therefore, in block 305, committee size and validators are 3
In the pictures, all APIs call block 304 and 305, if block number is the same, validators and committee values ​​are returned as equals.

image
image
image

## Types of changes

Please put an x in the boxes related to your change.

- [x] Bugfix
- [ ] New feature or enhancement
- [ ] Others

## Checklist

*Put an x in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.*

- [x] I have read the [CONTRIBUTING GUIDELINES](https://github.com/klaytn/klaytn/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla-assistant.io/klaytn/klaytn)
- [x] Lint and unit tests pass locally with my changes (`$ make test`)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Related issues

closes #1467

### CODE REVIEW

**Comment by blukat29** [comment]
@mckim19 Can we wrap the `header` -> `*Snapshot` conversion in a private method like below?
```go
// Returns the istanbul Snapshot that was used to verify given header.
// Note that the header #N is verified against Snapshot(N-1).
func (api *API) getSnapshotForHeader(header *types.Header) (*Snapshot, error)
```

**Comment by yoomee1313** [comment]
@mckim19 Can you edit the description? It would be nice if you explain the change more clearly.

dev
  * GetSnapshot(n) -> return snapshot of block n
  * GetCommittee(n) -> ...

PR
  * GetSnapshot(n) -> return ...
  * GetCommittee(n) -> ...

**Review by aidan-kwon — DISMISSED** [review]

**Comment by mckim19** [comment]
@blukat29 Thanks for your review. I did some refactoring for removing the duplicated code.

**Comment by mckim19** [comment]
@yoomee1313 Thanks for your review. I edited the description, and I hope it's good for understanding this PR.

**Review by JayChoi1736 — DISMISSED** [review]

File: consensus/istanbul/backend/api.go [hunk 1]
```diff
@@ -153,34 +181,15 @@ var (
...
-	} else if *number == rpc.PendingBlockNumber {
-		logger.Trace("Cannot get council of the pending block.", "number", number)
-		return nil, errPendingNotAllowed
-	} else {
-		header = api.chain.GetHeaderByNumber(uint64(number.Int64()))
-	}
-	// Ensure we have an actually valid block and return the council from its snapshot
-	if header == nil {
-		return nil, errNoBlockExist // return nil if block is not found.
+	previousBlockNumber := rpc.BlockNumber(number.Int64() - 1)
```
Comment (blukat29) [inline consensus/istanbul/backend/api.go:184]: Does it work with LatestBlockNumber and PendingBlockNumber?

**Comment by jiseongnoh** [comment]
I think GetSnapshot(blocknumber) should return api.istanbul.snapshot(blocknumber) because it is a getter of snapshot. a get method. 

The problem is that snapshot(blocknumber) N returns data that will be used to create the blocknumber N+1th block.
Therefore, if we want to get the data of blocknumber Nth block, we need to call snapshot(blocknumber-1), not snapshot(blocknumber).

GetCommittee(n) function returns the committee gathered from istanbul.snapshot(blockNumber-1), which is good.
However, GetCouncil(n) returns the value from istanbul.snapshot(blockNumber), which is not good. This PR fixes the return value of GetCouncil(n).
Another problem is GetValidators(n), which currently returns api.GetSnapshot(n). 
Maybe, it may be good for GetValidators(n) returns the value from istanbul.snapshot(blockNumber-1).


|                                	| current implement         	| New implement         	|
|--------------------------------	|------------------	|------------------	|
| api.GetSnapshot(n)                 	| api.istanbul.snapshot(n)   	| istanbul.snapshot(n) ? (n-1) ?  	|
| api.GetValidators(n)               	| api.GetSnapshot(n)   	| api.GetSnapshot(n) ? sb.snapshot(n-1) ? 	|
| GetDemotedValidators(n)        	| sb.snapshot(n)   	| sb.snapshot(n-1) 	|
| GetCouncil(n)                  	| sb.snapshot(n)   	| **sb.snapshot(n-1)** 	|
| GetCommittee(n)                	| sb.snapshot(n-1) 	| sb.snapshot(n-1) 	|
| GetBlockWithConsensusInfo..(n) 	| sb.snapshot(n-1) 	| sb.snapshot(n-1) 	|

File: consensus/istanbul/backend/api.go (hunk 1 above)
Comment (mckim19) [reply consensus/istanbul/backend/api.go:184]: No. I should change the logic.
Thanks for your review!

Comment (mckim19) [reply consensus/istanbul/backend/api.go:204]: I reflected in https://github.com/klaytn/klaytn/pull/1468/commits/ac760f0f64b9ef6a18c45efc4edd83299c8a1eb7.
Thank you.

Comment (blukat29) [reply consensus/istanbul/backend/api.go:204]: I still not convinced how this code works with LatestBlockNumber.

If you see [networks/rpc/types.go](https://github.com/klaytn/klaytn/blob/dev/networks/rpc/types.go#L135), LatestBlockNumber == -1 and PendingBlockNumber == -2.
If `number == Latest`, then `rpc.BlockNumber(number.Int64() - 1)` is `-2` (Pending), not `head - 1` (What you might intended).

How about factoring out rpc.Number parsing using something like this?

```go
// a private function, not a method of API nor APIExtension.

// Retrieve the header at requested block number
func headerByRpcNumber(number *rpc.Number) (*types.Header, error) {
	var header *types.Header
	if number == nil || *number == rpc.LatestBlockNumber {
		header = api.chain.CurrentHeader()
	} else if *number == rpc.PendingBlockNumber {
		logger.Trace("Cannot get snapshot of the pending block.", "number", number)
		return nil, errPendingNotAllowed
	} else {
		header = api.chain.GetHeaderByNumber(uint64(number.Int64()))
	}
	// Ensure we have an actually valid block and return its snapshot
	if header == nil {
		return nil, errUnknownBlock // return nil if block is not found.
	}
	return header, nil
}
```

Then use like

```go
func (api *APIExtension) GetCouncil(number *rpc.BlockNumber) ([]common.Address, error) {
    header, err := headerByRpcNumber(number)
    if err != nil {
        return nil, err
    }
    
    snap, err := api.GetSnapshotAtHash(header.ParentHash)
    if err != nil {
        logger.Error("Failed to get snapshot.", "hash", snap.Hash, "err", err)
        return nil, errInternalError
    }
    return append(snap.validators(), snap.demotedValidators()...), nil
}
```

File: consensus/istanbul/backend/api.go [hunk 2]
```diff
@@ -151,36 +179,33 @@ var (
 	errNoBlockNumber           = errors.New("block number is not assigned")
 )
 
-// GetCouncil retrieves the list of authorized validators at the specified block.
-func (api *APIExtension) GetCouncil(number *rpc.BlockNumber) ([]common.Address, error) {
+// GetSnapshot retrieves the state snapshot at a given block. The namespace is klay.
+func (api *APIExtension) GetSnapshot(number *rpc.BlockNumber) (*Snapshot, error) {
```
Comment (yoomee1313) [inline consensus/istanbul/backend/api.go:183]: What about making a private function? instead of adding new APIExtension method.
```suggestion
func getSnapshot(chain consensus.ChainReader, istanbul *backend, number *rpc.BlockNumber) (*Snapshot, error) {
```

File: consensus/istanbul/backend/api.go [hunk 3]
```diff
@@ -41,19 +41,23 @@ type API struct {
...
+	} else if *number == rpc.PendingBlockNumber {
+		logger.Trace("Cannot get snapshot of the pending block.", "number", number)
+		return nil, errPendingNotAllowed
 	} else {
 		header = api.chain.GetHeaderByNumber(uint64(number.Int64()))
 	}
 	// Ensure we have an actually valid block and return its snapshot
 	if header == nil {
-		return nil, errUnknownBlock
+		return nil, errUnknownBlock // return nil if block is not found.
```
Comment (yoomee1313) [inline consensus/istanbul/backend/api.go:58]: What about removing the comment? I think the code itself is clear to understand.

File: consensus/istanbul/backend/api.go [hunk 4]
```diff
@@ -63,41 +67,65 @@ func (api *API) GetSnapshotAtHash(hash common.Hash) (*Snapshot, error) {
...
 func (api *API) GetValidators(number *rpc.BlockNumber) ([]common.Address, error) {
-	snap, err := api.GetSnapshot(number)
+	previousBlockNumber := rpc.BlockNumber(number.Int64() - 1)
+
+	// get the snapshot of the previous block.
+	snap, err := api.GetSnapshot(&previousBlockNumber)
 	if err != nil {
-		return nil, err
+		logger.Error("Failed to get snapshot.", "hash", snap.Hash, "err", err)
+		return nil, errInternalError
```
Comment (yoomee1313) [inline consensus/istanbul/backend/api.go:82]: I think returning `err` is better because `GetSnapshot` is returns meaning error, too.
```suggestion
		return nil, err
```

File: consensus/istanbul/backend/api.go [hunk 5]
```diff
@@ -151,36 +179,33 @@ var (
...
-	// Calculate council list from snapshot
-	snap, err := api.istanbul.snapshot(api.chain, header.Number.Uint64(), header.Hash(), nil, false)
+// GetCouncil retrieves the list of authorized validators at the specified block.
+func (api *APIExtension) GetCouncil(number *rpc.BlockNumber) ([]common.Address, error) {
+	previousBlockNumber := rpc.BlockNumber(number.Int64() - 1)
+	// get the snapshot of the previous block.
+	snap, err := api.GetSnapshot(&previousBlockNumber)
 	if err != nil {
-		logger.Error("Failed to get snapshot.", "hash", header.Hash(), "err", err)
+		logger.Error("Failed to get snapshot.", "hash", snap.Hash, "err", err)
```
Comment (yoomee1313) [inline consensus/istanbul/backend/api.go:208]: If the code is changed to call `GetSnapshot`, then what about returning err instead of errInternalError?

File: consensus/istanbul/backend/api.go [hunk 6]
```diff
@@ -63,41 +67,65 @@ func (api *API) GetSnapshotAtHash(hash common.Hash) (*Snapshot, error) {
...
 		return nil, errUnknownBlock
 	}
+
 	return api.istanbul.snapshot(api.chain, header.Number.Uint64(), header.Hash(), nil, false)
 }
 
 // GetValidators retrieves the list of authorized validators with the given block number.
 func (api *API) GetValidators(number *rpc.BlockNumber) ([]common.Address, error) {
-	snap, err := api.GetSnapshot(number)
+	previousBlockNumber := rpc.BlockNumber(number.Int64() - 1)
```
Comment (jeongkyun-oh) [inline consensus/istanbul/backend/api.go:76]: Is this okay? It seems that `PendingBlockNumber.Int64()` returns `-2`.

File: consensus/istanbul/backend/api.go [hunk 7]
```diff
@@ -63,41 +67,65 @@ func (api *API) GetSnapshotAtHash(hash common.Hash) (*Snapshot, error) {
...
 // GetValidatorsAtHash retrieves the list of authorized validators with the given block hash.
 func (api *API) GetValidatorsAtHash(hash common.Hash) ([]common.Address, error) {
-	snap, err := api.GetSnapshotAtHash(hash)
+	header := api.chain.GetHeaderByHash(hash)
+	if header == nil {
+		return nil, errUnknownBlock
+	}
+
+	// get the snapshot of the previous block.
+	snap, err := api.GetSnapshotAtHash(header.ParentHash)
```
Comment (jeongkyun-oh) [inline consensus/istanbul/backend/api.go:95]: It is edge case, but what if the `hash` is genesis block's?

File: consensus/istanbul/backend/api.go (hunk 6 above)
Comment (jeongkyun-oh) [reply consensus/istanbul/backend/api.go:76]: Never mind. Just checked https://github.com/klaytn/klaytn/pull/1468/files#r913307162

File: consensus/istanbul/backend/api.go (hunk 2 above)
Comment (mckim19) [reply consensus/istanbul/backend/api.go:183]: Thanks for your review.
I will add a private function like what you and [blukat29](https://github.com/blukat29) recommended.

File: consensus/istanbul/backend/api.go (hunk 1 above)
Comment (mckim19) [reply consensus/istanbul/backend/api.go:172]: Reflected in https://github.com/klaytn/klaytn/pull/1468/commits/8b3142b26d372e9e286c0a5495e53a1d4a7915b0.
Thank you!

File: consensus/istanbul/backend/api.go (hunk 2 above)
Comment (mckim19) [reply consensus/istanbul/backend/api.go]: Reflected in https://github.com/klaytn/klaytn/pull/1468/commits/8b3142b26d372e9e286c0a5495e53a1d4a7915b0.
Thank you.

File: consensus/istanbul/backend/api.go (hunk 1 above)
Comment (mckim19) [reply consensus/istanbul/backend/api.go]: Reflected in https://github.com/klaytn/klaytn/pull/1468/commits/307820c288c4d7d1871a57d4b03f849deb46fdd0.
Thank you!

File: consensus/istanbul/backend/api.go (hunk 3 above)
Comment (mckim19) [reply consensus/istanbul/backend/api.go]: Removed the comment.
Thank you!

File: consensus/istanbul/backend/api.go (hunk 6 above)
Comment (mckim19) [reply consensus/istanbul/backend/api.go]: Thank you for your review. 
I fixed the problem that you mentioned. 
Reflected in https://github.com/klaytn/klaytn/pull/1468/commits/307820c288c4d7d1871a57d4b03f849deb46fdd0.
Thanks!

File: consensus/istanbul/backend/api.go [hunk 8]
```diff
@@ -63,41 +53,67 @@ func (api *API) GetSnapshotAtHash(hash common.Hash) (*Snapshot, error) {
...
+
+	previousBlockNumber := rpc.BlockNumber(header.Number.Uint64() - 1)
+
+	return getSnapshot(api.chain, api.istanbul, &previousBlockNumber)
 }
 
 // GetValidators retrieves the list of authorized validators with the given block number.
 func (api *API) GetValidators(number *rpc.BlockNumber) ([]common.Address, error) {
-	snap, err := api.GetSnapshot(number)
+	previousBlockNumber := rpc.BlockNumber(number.Int64() - 1)
```
[the remark this answers is not in the document]
Comment (mckim19) [reply consensus/istanbul/backend/api.go]: Thank you for your review.
I changed the logic about processing the number. 
It's reflected in https://github.com/klaytn/klaytn/pull/1468/commits/307820c288c4d7d1871a57d4b03f849deb46fdd0.
Thanks!

**Review by aidan-kwon — APPROVED** [review]

**Review by blukat29 — APPROVED** [review]
LGTM. Just update the table in PR body please.

**Comment by mckim19** [comment]
@blukat29 Thank you. I just updated it!

**Review by jiseongnoh — APPROVED** [review]

**Review by yoomee1313 — APPROVED** [review]
